# Generated by Django 3.2.1 on 2021-05-06 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilDeteksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil_hitung', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ttl', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=255)),
                ('pekerjaan', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TingkatDepresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depresi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pencegahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
                ('isi', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penanganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
                ('isi', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tingkat_depresi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tingkatdepresi')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPertanyaanJawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HasilDeteksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hasildeteksi')),
                ('Jawaban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jawaban')),
                ('Pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pertanyaan')),
            ],
        ),
        migrations.AddField(
            model_name='hasildeteksi',
            name='pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pengguna'),
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('cover', models.CharField(max_length=255)),
                ('isi', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
